# Generated by Django 5.1.6 on 2025-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_item_currency_order_discount_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='amount',
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=models.FloatField(default=0.0, help_text='Скидка в процентах от 0 до 100)'),
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.FloatField(default=0.0, help_text='Налог в процентах (0-100)'),
        ),
    ]
