# Generated by Django 5.1.6 on 2025-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_discount_amount_remove_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('gbp', 'GBP')], default='USD'),
        ),
    ]
